### ISSUE TITLE
Nutzer hinzufügen

### ISSUE THREAD

**Issue by pkorduan** [pkorduan/kvwmap_mvbio#1]
Nutzer einrichten in git und hinzufügen als Contributers

**Comment by dotto-git** [comment]
Wie kann ich andere Nutzer hinzufügen/einladen  oder ist dies nur durch den Ersteller des Repository möglich? Verfüge ich hier schon über erweiterte Rechte? Das löschen eines Issues ist mir z.B. aktuell nicht möglich. Wenn ich das richtig sehe habe ich aktuell den Staus als "Collaborator"

**Comment by pkorduan** [comment]
Das hinzufügen von Collaborators ist dem Eigentümer des Repositories vorbehalten. Ich kann das ganze Repository auf Sie übertragen und sie tragen mich pkorduan dann als contributor ein. Dann hätten Sie alle Rechte. Wollen wir das so machen?

**Comment by pkorduan** [comment]
Ich habe auch eingestellt, dass nur Nutzer, die Collaborators sind Beiträge zum Repository eintragen können.

**Comment by dotto-git** [comment]
mit der Übernahme des Repository, das können wir gern so machen

**Comment by dotto-git** [comment]
Vielen Dank, der Transfer war erfolgreich

**Comment by pkorduan** [comment]
ok dann ist der Issue abgeschlossen
