### ISSUE TITLE
Sachdateneingabe | Auswahl Bogenart KE: lrt

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#10]
Wenn Kartierebene „Lebensraumtypen“ ausgewählt wird darf die Auswahl der Bogenart nur:
o	Grundbogen sein

Aktuell ist hier auch die Auswahl von Grünlandbogen, Zustandsüberwachung, Verlustbogen und Kurzbogen möglich

**Comment by pkorduan** [comment]
Erledigt.
