### ISSUE TITLE
Sachdateneingabe | Auswahl Bogenart: Verlustbogen

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#12]
Ein Verlustbogen darf nur für schon bestehende Objekte auswählbar sein.

**Comment by pkorduan** [comment]
Wurde umgesetzt in JavaScript custom/kartierobjekte.js Funktion hideElementsByRecordCreation.

**Comment by Christin-Reinke** [comment]
Bei der Erfassung eines neuen Kartierobjektes kann zurzeit als Bogenart Verlustbogen ausgewählt werden. Diese Option muss für alle Kartierebenen entfernt werden. 
![grafik](https://user-images.githubusercontent.com/55788574/72412938-e66c2a00-376e-11ea-9374-7bd75b19ab9e.png)

**Comment by pkorduan** [comment]
Erledigt Verlustbogen taucht nicht mehr auf bei Neueingabeformular Kartierobjekt.
