### ISSUE TITLE
Fotoupload  | funktioniert nicht

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#14]
getestet in Stelle Kartierer bei der Erfassung eines gB als Grundbogen. Es sollte ein 1,4 MB großes Foto im jpg-Format hochgeladen werden:
- kann Foto in lokalem Verzeichnis anwählen
- es erscheint eine leere Fotovorschau
- öffnen des Fotos sagt fehlerhafte Datei, 
- JPG 207 Bytes groß

**Comment by rtrier** [comment]
Das Fotoupload funktioniert jetzt
