### ISSUE TITLE
Bogenansicht | Archiv LRT1315 - keine Fotoanzeige

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#16]
Fotos werden im Bogen nicht dargestellt

**Comment by pkorduan** [comment]
Das gilt nicht für alle. Ich schaue mir Beispiele an und prüfe ob die Bilder in der Lieferung dabei waren. Wenn nicht müssen diese noch nachgeliefert bzw. in den Dokumentenordner kopiert werden.

**Comment by dotto-git** [comment]
Fotos werde symbolisch dargestellt, das Bild lässt sich jedoch nicht laden oder anzeigen (Bsp.: lrtLRT1315-2-437) 
![grafik](https://user-images.githubusercontent.com/55746950/69801129-df955200-11d6-11ea-911b-9e9c4c899fd0.png)

**Comment by pkorduan** [comment]
Fehler behoben. Es kann zwar immernoch vorkommen, dass Bilder fehlen, aber nur wenn welche manuell auf der Festplatte gelöscht werden und nicht über die kvwmap Oberfläche.
