### ISSUE TITLE
LRT-Bewertung | LRT-Küste P.3.2.1

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#18]
Auswahlfelder nicht eindeutig:
in der Bewertungsanleitung ist nur die Gesamtschädigung bewertungsrelvant. 
Die jetzige Darstellung ist nicht eindeutig und lässt auch fehlerhafte Kombinationen zu.
z.B.: wenn ich die Gesamtschädigung auf >10% stelle ist auch möglich all 3 Einzelschädigungen auf >10% zu Stellen was nicht gehen kann bzw. die Frage sich stellt auf welche Fläche werden denn die Einzelschädigungen bezogen: auf die Gesamtfläche oder nur auf den Teil der geschädigten Gesamtflächen? 
**Mein Vorschlag:**
die prozentualen Zuordnungen zu den Einzelschädigungen weglassen und nur markieren welche Einzelschädigung auftritt, die Bewertung erfolgt ja schon jetzt nur über die Gesamtbewertung.

**Comment by tpolte** [comment]
In der zwischen mir und Ralf Trier abgestimmten Testversion hatten wir es so geregelt, dass keine der Angaben bei den Einzelschädigungen, über dem Gesamtwert liegen darf. Die Werte können alle genau diesen Wert haben, da sich die Ursachen der Schädigungen theoretisch überlagern können. Diese Lösung halte ich nach wie vor praktikabel. Ich halte es für wenig wahrscheinlich, dass jemand gleichzeitig alle Ursachen auf > 10 setzt, wenn der Gesamtwert auch nur 10 > beträgt.
