### ISSUE TITLE
Summe von Haupt- und Nebencode

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#21]
Für die Flächenanteile des Biotoptyps, bestehend aus Haupt- und Nebencode, sind Angaben über und unter 100 % auswählbar. Laut der Biotoptypen-Kartieranleitung (S. 21) muss die Summe der Flächenanteile stets 100 % betragen.

Beispiel für eine Summe der Flächenanteile von 10 %: Kvwmap_demo: Ob-jekt-Code Demo_MVBIO-Pro-L1_Demo_M-V-1 (Nutzer: demo PW: mvbio)

**Comment by rtrier** [comment]
Muss/soll der Kartierer während der Erfassung gezwungen sein, die Anteile so einzugeben, dass sich eine Summe von 100% ergibt, oder ist es besser, wenn die Prüfung während der Änderung des Bearbeitungsstandes (Freigabe) erfolgt?

**Comment by dmueller-up** [comment]
Am sinnvollsten ist es wohl, wenn es gleich bei der Eingabe erzwungen wird, spätestens aber bei der Statusänderung "Zur Info freigegeben" durch den Kartierer. Letzteres ist eigentlich gleichwertig, falls das einfacher umzusetzen ist.

**Comment by rtrier** [comment]
Alert, wenn Summe>100 überschritten, Die Werte werden noch gespeichert. Bei Statusänderung "Zur Info freigegeben" ist zu prüfen, ob der Wert=100% ist. Ist dies nicht der Fall wird das Objekt nicht zur Info freigegeben werden.
