### ISSUE TITLE
Gefährdungscode YWC Dränung

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#24]
Das Bewertungskriterium 3.1.1 „Veränderung des Wasserregiems“ wird durch die Vergabe von Gefährdungscodes, die im GB eingegeben werden, bewertet. Dieses Kriterium wird in den LRT 1340, 6410 und 6440 betrachtet. 
Der Gefährdungscode YWC „Dränung“ wird nicht als Veränderung des Wasserregiems gewertet. Dadurch hat die Auswahl dieses Codes auch keine Auswirkung auf die Bewertung des Kriteriums. Ist das fachlich richtig?

Beispiel: Kvwmap_demo: Objekt-Code Demo_MVBIO-Pro-L1_Demo_M-V-1 (Nutzer: demo PW: mvbio)

**Comment by tpolte** [comment]
Bei den Offenland-LRT 1340, 6410 und 6440 handelt es sich um mooriges oder anmooriges Feuchtgrünland, das i.d.R. über Gräben entwässert und eher nicht oder weniger über unteridrisch verlegte Dränrohre. Im Beispielbogen ist neben der Drainung als Gefährdung auch die Entwässerung durch Grabensystem angegeben, was sich negativ auf die Bewertung auswirkt. Trotzdem wäre es mal interessant zu prüfen, ob YWC bei den betreffenden LRT, z.B. in der Kartierkampagne BK1315, irgendwann mal als einzige Gefährdung angegeben wurde.
