### ISSUE TITLE
Bewertungskriterium 3.2.1 Stoffeinträge möglich durch fehlende Pufferstrukturen

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#27]
Das Bewertungskriterium „3.2.1 Stoffeinträge möglich durch fehlende Pufferstrukturen“ wird in den LRT 1340, 2310, 2330, 4010, 4030, 5130, 6120, 6210, 6230, 6240, 6410, 6440 und 6510 betrachtet. 
Bei fehlenden Strukturen kann der Hauptparameter „Beeinträchtigungen“ um eine Stufe abgesenkt werden. Meiner Meinung nach fehlt ein Infobutton mit folgenden Angaben:
- die Freieingabe ist optional
- die Freieingabe muss mit dem Radiobutton übereinstimmen
- Bedeutung der Angaben: 0 = keine Herabstufung, -1 = Herabstufung

Beispiel: Kvwmap_demo: Objekt-Code Demo_MVBIO-Pro-L1_Demo_M-V-2 (Nutzer: demo PW: mvbio)

**Comment by tpolte** [comment]
In der Bewertungsanleitung M-V und in den dortigen Schemata werden keine Schwellenwerte angegeben. Im MVBIO (TH Handbuch) gibt es einen Bezug zu Schwellenwerten, wenn ich richtig lese, eine Absenkung bei allen Werten < 75%. Das ist so in MVBIO5 und MVBIOPro umgesetzt. Da die Herkunft dieses Schwellenwertes nicht mehr nachvollziehbar ist und damit bisher gearbeitet wurde, bleibt dieser bis auf Weiteres so bestehen. Die Freieingabe bringt keinen Mehrwert und kann gestrichen werden. Die folgendermaßen erweiterte Erläuterung 'Pufferstrukturen in % der Umgebung (Herabstufung von 3., wenn < 50%)'  bleibt aber erhalten.
