### ISSUE TITLE
LRT 2330: Bewertung von Achillea millefolium agg.

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#28]
Für den LRT 2330 wird Achillea millefolium agg. als lebensraumtypische Art angegeben. Wird nur Achillea millefolium in die Pflanzeneingabe eingetragen, wird diese nicht mitgezählt. Ist das fachlich richtig?
Kvwmap_demo: Objekt-Code Demo_MVBIO-Pro-L1_Demo_M-V-3 (Nutzer: demo PW: mvbio)

**Comment by dmueller-up** [comment]
Achillea millefolium muss mitgezählt werden, da zu Achillea millefolium agg. gehörig

**Comment by rtrier** [comment]
Achillea millefolium wurde in die Tabelle mit der Zuordnung lebensraumtypische Arten zum LRT-Code hinzugefügt. Damit sollte die Zählung korrekt sein, solange nicht beides eingegeben wird.
