### ISSUE TITLE
Angaben zur Gefährdung im LRT-Grundbogen

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#29]
Im den LRT-Grundbögen können in der Kategorie Gefährdung Gefährdungscodes eingegeben werden. Aber auch wenn man einen Gefährdungscode gesetzt hat, kann ein Häkchen bei „keine Gefährdung“ gesetzt werden. Es erscheint keine Fehlermeldung. Somit können widersprüchliche Angaben gemacht werden.

**Comment by rtrier** [comment]
erledigt
