### ISSUE TITLE
Pflanzeneingabe | Sortierung

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#3]
Eingabe sortiert aktuell nach DVZ (Dominant- Vereinzelt-Zahlreich)  --> richtig ist: DZV (Dominant – Zahlreich – Vereinzelt)

**Comment by pkorduan** [comment]
OK, habe folgendes geändert: Bezeichnung des Attributes geändert von DVZ auf DZV und Sortierung auf DZV in Layerdefinition angepasst. Neue Layerdefinition von Pflanzenvorkommen:
```
SELECT
  kartierung_id, pflanzenart_id, gsl.abbreviat, dzv, cf, nummer, fsk, rl, tax, bav
FROM
  pflanzenvorkommen pv JOIN
  pflanzenarten_gsl gsl ON pv.pflanzenart_id = gsl.species_nr
WHERE
  true
ORDER BY
  (CASE WHEN dzv = 'D' then 1 ELSE case when dzv = 'Z' then 2 ELSE 3 end end), nummer
```
Umgesetzt in Produktion (kvwmap) wird noch übernommen in die anderen Umgebungen.
