### ISSUE TITLE
LRT 2330: Bewertung von Festuca ovina s. str.  

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#30]
Für den LRT 2330 wird Festuca ovina s. str.  als lebensraumtypische Art in der Bewertungsanleitung angegeben. Dieses Synonym (?) ist in der Pflanzenauswahl und in GermanSL nicht enthalten. Ist Festuca ovina die richtige Entsprechung?
Kvwmap_demo: Objekt-Code Demo_MVBIO-Pro-L1_Demo_M-V-3 (Nutzer: demo PW: mvbio)

**Comment by dmueller-up** [comment]
Ich würde eigentlich davon ausgehen, dass Festuca ovina s. str. = Festuca ovina
Allerdings sind in MVBIO Festuca ovina s. str. + Festuca ovina + Festuca ovina agg. enthalten. Bitte zur Klärung Tom Polte einbeziehen!

**Comment by tpolte** [comment]
Auch das ehemals beschrieben Festuca ovina s. str. (im engeren Sinne) wird heute schon wieder in mind. 2 Kleinarten aufgeteilt, u.a. anderem in Festuca ovina ssp. ovina und in Festuca ovina ssp. guestfalica. Letztgenannte Unterart taucht auch im BWS für den LRT 2330 auf und hat in der neuen German SL das Synomym Festuca guestfalica*guestfalica. Mit Festuca ovina s. str. muss somit Festuca ovina ssp. ovina gemeint sein und diese Unterart entspricht laut neuer German SL Festuca ovina.

**Comment by Christin-Reinke** [comment]
Festuca ovina ist bereits in der Referenzliste enthalten und wird gezählt. Damit ist dieser Issue aus meiner Sicht geklärt.
