### ISSUE TITLE
Pflanzeneingabe begrenzt LRT 5130 

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#38]
Für den LRT 5130 werden 117 lebensraumtypische Pflanzen in der Bewertungsanleitung angegeben. Nachdem 99 Pflanzen im Bewertungsbogen gezählt wurden, können keine weiteren Pflanzen mehr eingegeben werden. 
Folgende Fehlermeldung wird angezeigt:  
Fehler bei der Abfrage der PostgreSQL-Datenbank:
FEHLER: Feldüberlauf bei Typ »numeric« DETAIL: Ein Feld mit Präzision 2, Skala 0 muss beim Runden einen Betrag von weniger als 10^2 ergeben.
Aufgetreten bei SQL-Anweisung:
SET search_path = mvbio, public;SET datestyle TO 'German';LOCK TABLE pflanzenvorkom-men IN SHARE ROW EXCLUSIVE MODE;INSERT INTO pflanzenvorkommen (pflanzenart_id, dzv, cf, kartierung_id) VALUES ('82022', 'V', 'f', '252589')

Kvwmap_demo: Objekt-Code Demo_MVBIO-Pro-L1_Demo_M-V-6 (Nutzer: demo PW: mvbio)

**Comment by rtrier** [comment]
Die Beschränkung ergab sich daraus, dass in das Feld für die Anzahl lrt-typischer Arten nur Werte bis 99 speicherbar waren (Tabelle mvbio.bewertungen_offenland)
