### ISSUE TITLE
LRT- Einzelparameterbewertung - Darstellung IE11 (Microsoft)

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#49]
Problem:
die Echtzeit-Einzelparameterbewertung im LRT-Bewertungsbogen wird nicht im Microsoft IE11 angezeigt.

Hinweis:
Ich hoffe ja das sich das Problem "verwächst" und sich mit der Einführung von Windows10 (Edge - Browser)  von selbst löst. Das Problem ist jedoch das die Nutzer in der Landesverwaltung nicht die Wahl haben welche Software Sie verwenden und aktuell der IE11 der Standardbrowser ist. Weiter ist es auch nicht wirklich absehbar wann konkret die Umstellung auf Windows 10 in der Landesverwaltung erfolgt, meines Wissens ist dies für das 1.Quartal 2020 angekündigt. Sollte sich das bestätigen,ist aus meiner Sicht keine Anpassung notwendig.
Ich bitte deshalb hier erstmal nur den Aufwand zu prüfen.

Grundsätzlich sollte MVBIO-Pro mit Microsoft Edge, Mozilla Firefox und Google Chrome in den jeweils aktuellen Versionen kompatibel sein.

**Comment by rtrier** [comment]
Ich habe den Code so angepasst der IE11 unterstützt wird. Ich habe aber nicht alles getestet. Die Darstellung des Pfeils bei Erhöhung/Verringerung wird nicht angezeigt.
