### ISSUE TITLE
Sachdateneingabe | Überlagerungscode

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#5]
Eingabe alle Biotoptypen muss möglich sein, aktuell nur UC auswählbar

**Comment by pkorduan** [comment]
Die Tabelle, die für die UC Auswahllisten verwendet wird, wird durch die Tabelle mvbio.code_biotoptypen_ueberlagerungscodes ausgetauscht. Wie das geht wurde Daniel Otto erklärt und im MVBio Wiki unter Administration beschrieben.
