### ISSUE TITLE
Bewertungskriterium 1.1.1 Deckung lebensraumtypischer Vegetation

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#53]
Zur Bewertung des Kriteriums „1.1.1 Deckung lebensraumtypischer Vegetation“ in den Moor-Lebensraumtypen wird die Deckung in Prozent aus den Haupt- und Ne-bencodes abgeleitet. Im Bewertungsbogen wird die Prozentzahl korrekt dargestellt, aber der Radiobutton wird nicht angepasst. Da die Bewertung scheinbar über den Radiobutton erfolgt, wird der Parameter falsch bewertet. 
Betroffen sind die Moor-Lebensraumtypen 7120, 7140, 7150, 7210, 7230.

**Comment by rtrier** [comment]
erledigt
