### ISSUE TITLE
Pflanzeneingabe LRT 7150 - Referenzliste LRT

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#56]
Welche Pflanzen bewertungsrelevant sind, ist vom eingegebenen Hauptcode abhängig.
Lautet der Hauptcode „TFB Sumpfbärlapp-Feuchtheide“ werden nur die Arten gezählt die mit „SBFH“ in der Referenzliste gekennzeichnet wurden. In der Bewertungsanleitung sind diese Arten mit  einem "*" markiert. Lautet der Hauptcode „MSS Torfmoos-Schwingrasen“ werden nur die Arten gezählt die **nicht** mit „SBFH“ gekennzeichnet wurden. Für beide Fälle werden Testdatensätze in Demo angelegt.
Besonders charakteristische Arten werden in der Referenzliste mit "+" oder "+KA" gekennzeichnet.

In der Referenzliste sind folgende Fehler:
Drosera longifolia „+“ fehlt
Eriophorum angustifolium „+“ fehlt (SBFH ist richtig)
Menyanthes trifoliata „+“ fehlt 
Sphagnum recurvum agg. „+“ fehlt

**Comment by dotto-git** [comment]
@tpolte 
Sind dir bei den LRT Fälle bekannt wo eine von der FFH-Bewertungsanleitung abweichende bewertungsrelvante Artauswahl getroffen wurde? Dies sollte nicht sein und soll auch zukünftig nicht erfolgen. Grundsätzlich könnnen Änderungen nur übernommen werden wenn die entsprechenden Anleitungen vorher geändert werden. Aber das es nicht sein soll, heißt ja nicht das es nicht trotzdem gemacht wurde.

Die Anpassung der Referenzlisten kann durch mich über den Adminaccount in MVBIO-Pro durchgeführt werden, deshlab habe ich hier noch das Label  "LUNG-ADMIN" eingeführt.

**Comment by tpolte** [comment]
1. Ich bin bis jetzt davon ausgegangen, dass die Vorgaben aus der Bewertungsanleitung (2012) auch so in MV-BIO übernommen wurden. Eine abweichende bewertungsrelevante Artauswahl ist mir nicht bekannt, bzw. nicht dokumentiert.
2. Ich kann nicht nachvollziehen, warum beim LRT 7150 nur die mit * gekennzeichneten Arten gezählt werden. Von den 9 *Gefäßpflanzen sind lt. BKA 2013 ( TFB, MSS) nur 3 ausschließlich für TFB charakteristisch. Die anderen 6 sind auch bei MSS als lrt-typisch gelistet. Warum sollten sie dort also nicht mitgezählt werden. Andererseits fehlen bei den mit * gekennzeichneten Arten 3 Arten, die aussschließlich für TFB charaktersitisch sind. Diese finden bisher bei der Bewertung keine Berücksichtigung. Das kann ich nicht nachvollziehen. Hoffentlich ist diese Ungereimtheit nicht die Spitze eines Eisberges, sonst gibt es noch erheblichen Überarbeitungsbedarf. Problematisch ist, dass die bisherigen Bewertungen alle nach der Bewertungsanleitung von 2012 getätigt wurden. Falls wir jetzt etwas ändern, spiegeln Neubewertungen, z.B. bei der Zustandsüberwachung, nicht tatsächliche Veränderungen wieder.
Ergo - es muss erstmal alles 1:1 von MV-BIO 5 in MV-BIO-Pro übernommen werden, bevor die Bewertungsanleitung nicht überarbeitet wurde. Fehler, die uns auffallen, müssen notiert bzw. dokumentiert werden. Ich muss mich scheinbar bei einer Fortschreibung der Bewertungsanleitung auch intensiv mit der Ableitung von Bewertungen aus den Pflanzenlisten bzw. der Interpretation der Ableitung in MV-BIO beschäftigen. 
3. In der Bewertungsanleitung steht 'Arten mit * gelten nur für TFB'. Das muss im Umkehrschluss nicht heißen, dass die anderen Arten nicht gelten. Sonst müsste es doch heißen: 'Für TFB gelten nur Arten mit *', oder?

**Comment by Christin-Reinke** [comment]
Referenzliste wurde durch LUNG Admin angepasst. 
Drosera longifolia, Eriophorum angustifolium, Menyanthes trifoliata und Sphagnum recurvum agg. wurden als besonders Charakteristisch markiert. Pflanzen werden jetzt für beide Hauptcodes (MSS und TFB) richtig gezählt.
