### ISSUE TITLE
Bewertungskriterium 3.2.5 Deckung von Gehölzen ohne Zwergsträucher für LRT 7150

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#57]
Bewertungskriterium 3.2.5 Deckung von Gehölzen ohne Zwergsträucher für LRT 7150
Die Auswahlmöglichkeiten für diesen Parameter entsprechen nicht der Bewertungsanleitung (S. 85). Der Erhaltungszustand C sieht eine Deckung von <= 30 % vor. So war es auch in MVBIO 5 umge-setzt. In MVBIO Pro werden aber auch die Auswahlfelder > 30 % mit C bewertet. Ist das fachlich begründet oder soll die Bewertung nach der Bewertungsanleitung erfolgen?
Siehe auch Issue #33

**Comment by tpolte** [comment]
Die Bewertung soll nach der Bewertungsanleitung erfolgen. Auswahlfelder > 30 % sind demnach beim LRT 7150 nicht unbedingt notwendig, aber unschädlich, wenn Sie, wie zurzeit umgesetzt, mit 'C' bewertet werden.
