### ISSUE TITLE
Sachdateneingabe | Auswahl Bogenart KE: gB

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#6]
Wenn Kartierebene „geschützte Biotope" ausgewählt wird darf die Auswahl der Bogenart nur:
o	Grundbogen
o	Kurzbogen sein
--> Aktuell ist hier auch die Auswahl von Grünlandbogen und Zustandsüberwachung möglich

**Comment by pkorduan** [comment]
Ist erledigt.
