### ISSUE TITLE
LRT 2190 | Bewertungsbogen kann nicht erstellt werden 

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#60]
Für den LRT 2190 kann in Demo kein Bewertungsbogen erstellt werden. 
Objektcode: Demo_MVBIO-Pro-L1_Demo_M-V-36 (Nutzer: demo PW: mvbio)

Folgende Fehlermeldung erscheint:
Fehler bei der Abfrage der PostgreSQL-Datenbank:
FEHLER: Feldüberlauf bei Typ »numeric« DETAIL: Ein Feld mit Präzision 2, Skala 0 muss beim Runden einen Betrag von weniger als 10^2 ergeben.
Aufgetreten bei SQL-Anweisung: 				SET search_path = mvbio, public;SET datestyle TO 'German';LOCK TABLE bewertungen_kueste IN SHARE ROW EXCLU-SIVE MODE;INSERT INTO bewertungen_kueste (kartierung_id) VALUES ('252625')

**Comment by rtrier** [comment]
In der Tabelle bewertungen_kueste konnte ein Feld keine Zahlen > 99 speichern.
ALTER TABLE mvbio.bewertungen_kueste  ALTER COLUMN t211_1_1 TYPE numeric (3, 0);
