### ISSUE TITLE
Bewertungskriterium 2.1.1 Gesamtanzahl lr-typischer Pflanzenarten für LRT 3150

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#62]
Die Anzahl der lr-typischer Pflanzenarten wird je nach eingegebenen Überlagerungscode 1 unterschiedlich bewertet. Bei Eingabe von Überlagerungscodes für Altwasser und Abgrabungsgewässer (USA, USS, USL, USB, USK) wird die Anzahl nicht richtig bewertet. Gibt man im Zahlenfeld des Bewerungsbogen eine „4“ ein, findet keine Bewertung des Parameters statt. Laut Bewertungsanleitung müsste es jedoch mit einem B bewertet werden. Das Problem tritt nur bei vier Arten auf, alle anderen Anzahlen werden korrekt bewertet.

Kvwmap_demo: Objekt-Code: Demo_MVBIO-Pro-L1_Demo_M-V-41 (Nutzer: demo PW: mvbio)

**Comment by rtrier** [comment]
erledigt
