### ISSUE TITLE
Bewertungsbogen Überschrift und Link

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#68]
Bitte in der Überschrift des Bewertungsbogens den LRT hinzufügen. Zum Beispiel „Bewertung Offenland LRT 1340“.
Außerdem die Bezeichnung des Links „zum Kartierobjekt“ in „zum Grundbogen" ändern.

**Comment by rtrier** [comment]
Der LRT wird jetzt oben in der Tabelle angezeigt.
