### ISSUE TITLE
Verlustbögen | Erstellung/ Workflow

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#75]
Wenn man einen Verlustbogen erstellen will, muss es zuvor immer einen Grund- oder Kurzbogen zum verloren gegangenen Biotop geben. 
Der Workflow sollte folgendermaßen aussehen:
1.	im Archiv wird der Grund- oder Kurzbogen gesucht
2.	Die Daten werden in einen Verlustbogen in die aktuelle Kartierung gehoben. Dazu wäre ein Link „Verlustbogen erzeugen“ an der im Bild markierten Stelle geeignet.
![grafik](https://user-images.githubusercontent.com/55788574/69416514-1838b580-0d17-11ea-9389-00086fc57639.png)

3.	Die Grundinformationen aus dem Grundbogen werden dabei übernommen. Die Eingabefelder „Verlustursachen“ und „Beschreibung der Verlustursachen“ werden hinzugefügt. (vgl. MVBIO 5)

Verlustbögen sollen nicht neu erfasst werden können.  Bei der Erfassung eines neuen Datensatzes kann zurzeit aber auch die Bogenart Verlustbogen ausgewählt werden.

**Comment by pkorduan** [comment]
Der Link zum Anlegen eines neuen Verlustbogen ist eingebaut. Es fehlt aber noch die Anlage in der richtigen Bogenart mit den zusätzlichen Attributen „Verlustursachen“ und „Beschreibung der Verlustursachen“ und den Rechten zum ändern nur dieser Daten. Is in Arbeit.

**Comment by pkorduan** [comment]
Attribute Verlustursachen und Beschreibung der Verlustursachen in den Layer Kartierobjekte eingefügt und beim Klick auf "Als Verlustbogen übernehmen" wird bogenart_id = 3 (Verlustbogen) gesetzt und diese Attribute angezeigt. Wird in demo wirksam, wenn Änderungen von Produktion in Demo überspielt werden.

**Comment by Christin-Reinke** [comment]
In Demo erzeugt der Link „Verlustbogen anlegen“ einen Grundbogen anstatt eines Verlustbogens.

**Comment by pkorduan** [comment]
Ist in dev eingebaut. Da dev Demo wird setze ich den Issue auf erledigt.
