### ISSUE TITLE
Stellenverwaltung | Kartiergebiete anlegen

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#79]
Kartiergebiete können zurzeit nur in der Stelle Prüfung angelegt werden. Es müssen aber auch aus der Stelle Koordinierung Kartiergebiete angelegt werden können, damit die Koordinatoren (z. B. die beauftragten Büros) Kartiergebiete für die einzelnen Kartierer anlegen können.

**Comment by pkorduan** [comment]
Dazu geht mal als Admin in die Stelle Admin und die Layerverwaltung > Layer anzeigen > Layer: Kartiergebiete > Reiter: Rechte uns setzt für die Stelle Koordinierung die Layerzugriffsrechte "Datensätze erzeugen und löschen" Nach dem Speichern kann man in der Stelle auch neue Kartiergebiete anlegen.
