### ISSUE TITLE
Bogenansicht | Archiv

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#8]
Grundbögen / Kurzbögen 
Bei Bogenansicht keine definierte Bogenstruktur --> aktuelll unstrukturierte Anzeige von Spaltenbezeichungen der Datentabelle

**Comment by Christin-Reinke** [comment]
Bitte auch in Demo umsetzten, damit Testdaten aus der BK1 und 1315 gehoben werden können. Im Moment können nur Grundbögen der BK1 übernommen werden. Für alle anderen Bogenarten (Kurzbögen, Verlustbögen, Grünlandbögen) aus der BK1 bzw. 1315 ist die Funktion „Daten in neue Kartierung übernehmen“ nicht vorhanden.

**Comment by pkorduan** [comment]
Da die Bogenstruktur in BK1 entwickelt wurde und es immer wieder noch zu Änderungen kam, wurde immer nur dieser bearbeitet. Der Plan ist die Einstellungen wenn sie bei BK1 fertig sind auf alle anderen zu übertragen. Für die Übertragung der Attributeinstellungen wurde eine Funktion geschrieben die unter der Liste der Attribute im Attributeditor zu finden ist (Zauberstab). Bei Klick auf den Button erscheint eine Auswahlliste für den Layer für den die Einstellungen übernommen werden sollen. Hier Layer auswählen und auf Button "Attributeinstellungen für ausgewählten Layer übernehmen". Diese Funktion wird zur Zeit nur von GDI-Service bedient.

**Comment by pkorduan** [comment]
Struktur für Grundbögen und Kurzbögen wurde für alle Kampagnen übernommen und von dev auf prod eingespielt. Jetzt sollten alle Sachdatenanzeigen der Archivlayer strukturiert angezeigt werden können und die LInks zur Übernahme von Grundbögen und Verlustbögen erscheinen.
