### ISSUE TITLE
Bearbeitungsstufen | Durch Kartierer freigegeben

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#81]
Wenn ein Kartierobjekt vom Kartierer freigegeben wurde, wird es in der Stelle Koordinierung nicht angezeigt. 
Der Grundbogen mit dem Objektcode Demo_MVBIO-Pro-L2_GB_Demo_M-V-92 wurde mit dem Account Max Mustermann in die Bearbeitungsstufe ‚durch den Kartierer freigegeben‘ gehoben. Logge ich mich mit meinem eigenen Account in der Stelle Koordinierung ein, wird der Bogen nicht angezeigt. Nur in der Stelle Prüfung ist er sichtbar. Auch im Account Max Mustermann sieht man den Bogen nicht mehr in der Liste mit den durch Kartierer freigegeben Objekten.

**Comment by pkorduan** [comment]
Das Problem ist gelößt. Andere Kartierer können jetzt auch Kartierungen von anderen sehen, die nicht mehr nur "in Bearbeitung" sehen und Koordinierung kann für Koordinierung freigegebene sehen. Es war eingestellt, dass man nur eigene sieht, was natürlich für Koordinierung Quatsch ist. Die müssen ja alle sehen können, die für sie freigegeben sind.

**Comment by Christin-Reinke** [comment]
In der Stelle Koordinierung funktioniert es jetzt. 
Aber als Kartierer (Max Mustermann) ist der Bogen nicht sichtbar. Laut der Übersicht im Wiki (https://mvbio.de/wiki/doku.php?id=dokumentation) müsste der Kartierer das Kartierobjekt so lange sehen können bis es Archiviert wird.

**Comment by pkorduan** [comment]
Das kann ich so nicht nachvollziehen. Ich kann Demo_MVBIO-Pro-L2_GB_Demo_M-V-92 sehen und auch ein eben von mir selbst angelegtes objekt Demo_MVBIO-Pro-L2_GB_Demo_M-V-113. Beide sind in der Stelle des Kartierers unter "in Liste anzeigen"  ohne Filter und mit Filter "Durch Kartierer freigegeben" zu sehen.

**Comment by Christin-Reinke** [comment]
Jetzt funktioniert es bei mir auch.
