### ISSUE TITLE
Fotoupload funktioniert nicht, Speicher-Button unklar

### ISSUE THREAD

**Issue by Christin-Reinke** [pkorduan/kvwmap_mvbio#82]
Der Fotoupload im System Demo funktioniert nicht mehr. Dateien können ausgewählt, aber nicht gespeichert werden. Folgende Fehlermeldung erscheint, wenn man auf ‚speichern‘ klickt. 
 
![grafik](https://user-images.githubusercontent.com/55788574/72058873-2d6ea100-32d1-11ea-8f6a-f3f57260a7ae.png)

Im Bogen mit Objekt-Code Demo_MVBIO-Pro-L1_Demo_M-V-3 sind bereits seit längerem zwei Bilder gespeichert. Will man ein weiteres Foto hochladen und klickt dazu auf ‚neu‘ werden zwei Schaltflächen zum Speichern dargestellt. Es ist nicht eindeutig auf welchen man klicken muss. Klickt man auf den oberen Button, wird die Maske zum Fotos hochladen geschlossen. Klickt man auf den unteren Button erscheint die Fehlermeldung. Es sollte klar erkennbar sein wann man welchen Button benutzen muss.

 
![grafik](https://user-images.githubusercontent.com/55788574/72058896-38293600-32d1-11ea-9aea-dd89c312f232.png)

**Comment by pkorduan** [comment]
Der Bug beim Hochladen der Fotos wurde behoben. Es lag an einem Trigger, der geschrieben wurde für den Update der Anzahl der Fotos im Kartierobjekt und der war auch für das Insert neuer Fotos verwendet worden. Der Trigger wurde so umgeschrieben, dass er nun nur noch bei INSERT und DELETE von fotos anspringt. Die Anzahl der Fotos wird aber erst nach dem Reload eines Sachdatenformulars richtig angezeigt.

**Comment by pkorduan** [comment]
An der Problematik, dass es zwei Speicher-Buttons gibt wird noch gearbeitet. Es sind im Moment noch zwei, weil die Fotos eigentlich Subforms sind. Ein Speichern Button ist zum Speichern von neuen Bildern wenn ein neues hinzugefügt wird und der andere zum Speichern der Änderungen an Subforms. Die Subforms sieht man aber nur wenn man auf ein Bild klickt. Wir bauen das so um, dass der Speicher-Button für die Subforms nur angezeigt wird, wenn auch wirklich ein Subform offen zur Bearbeitung ist und darin etwas geändert wurde. Aber auch hier kann es dann sein, dass da dann zwei sind, nämlich einer wenn man gerade dabei ist ein neues Bild hochzuladen und zusätzlich noch ein Subform auf macht um ein anderes Foto auszutauschen. Aber das wird dem Nutzer dann sicher klar sein, dass da dann auch zwei verschiedene Speicher-Button da sind.

**Comment by pkorduan** [comment]
Zum Upload der Fotos gibt es ein neues Video https://youtu.be/_VoVXYcL0pw. Siehe Wiki https://mvbio.de/wiki/doku.php?id=videos

**Comment by pkorduan** [comment]
Die zwei Speicher-Button Problematik ist jetzt auch gelöst.

**Comment by mtaschem** [comment]
gelesen

**Comment by dotto-git** [comment]
dies ist bloß ein Test der Benachrichtungsfunktion von Github und wird gleich wieder gelöscht
