### ISSUE TITLE
Schulung | Nutzer-WIKI anlegen

### ISSUE THREAD

**Issue by dmueller-up** [pkorduan/kvwmap_mvbio#89]
Eigenes öffentliches WIKI anlegen
Bearbeiter (LUNG/UmweltPlan) Zugangsdaten zuschicken

**Comment by pkorduan** [comment]
Ist angelegt und erreichbar unter https://mvbio.de/nutzerdoku.
Folgende Nutzer sind mit angegebenen Rechten angelegt.
  | aschumann | André Schumann | andre.schumann@lung.mv-regierung.de | user, editor
  | dmueller | Dirk Müller | dm@umweltplan.de | user, admin
  | dotto | Daniel Otto | daniel.otto@lung.mv-regierung.de | user, editor
  | mtaschemski | Mathias Taschemski | mathias.taschemski@lung.mv-regierung.de | user, editor
  | pkorduan | Peter Korduan | peter.korduan@gdi-service.de | admin, user
  | tpolte | Tom Polte | tom.polte@lung.mv-regierung.de | user, editor
Die Zugangsdaten wurden am 7.2. per E-Mail versendet.
