### ISSUE TITLE
Kurzbogen | Schutzmerkmale

### ISSUE THREAD

**Issue by dotto-git** [pkorduan/kvwmap_mvbio#94]
Der Kurzbogen soll wie der Grundbogen als Auswahl der Schutzmerkmale neben "geschützt nach §20 NatschAG" auch die Auswahl "geschützt nach FFH-Richtlinie" enthalten

**Comment by pkorduan** [comment]
Ist umgesetzt. Die Auswahl von Schutz_FFH kommt jetzt außer Bogenart 5 Grünlandbogen, weil das bei Schutz §20 auch so ist.
