### ISSUE TITLE
Kartiergebiete anlegen/anzeigen

### ISSUE THREAD

**Issue by mtaschem** [pkorduan/kvwmap_mvbio#96]
ist, unabhängig von der Stelle, nicht möglich da folgende Fehlermeldung erscheint

![grafik](https://user-images.githubusercontent.com/60427742/75856947-aaac2300-5df5-11ea-805a-63cc02d9b395.png)

**Comment by pkorduan** [comment]
Wurde behoben. Zur Verwendung der Nutzertabelle aus mysql muss mysql_fdw im Postgres-Container installiert sein. Das wurde im Zuge der Entwicklung gemacht, jedoch nur im laufendem Container. Nach dem Neustart war die Installation wieder weg. Es wurde jetzt ein spezielles Images von pkorduan/postgis:9.6-2.5-mysql_fdw erzeugt welches die Installation von mysql_fdw enthält und in env_and_volumes vom Postgres-Container eingetragen. Damit solle beim Neustart des Postgres-Containers das nächste mal mysql_fdw mit Verfügbar sein und der Fehler nicht mehr auftreten.
